Add an option to dump the results of the tests to a JSON machine-readable file.
google/gtest-parallel pull request #14
Opened 2016-12-05 14:24 UTC by ehlemur

Add an option to dump the results of the tests to a JSON machine-readable file.
The format of the file is described in https://www.chromium.org/developers/the-json-test-results-format

2016-12-05 14:24 UTC, ehlemur commented
@kwiberg PTAL

2016-12-05 14:25 UTC, ehlemur commented
@pbos

2016-12-05 16:49 UTC, pbos commented on gtest-parallel
> +  test_results.dump_to_file(options.dump_json_test_results)
Can you hold on to this file handle for the duration of the tests? CollectTestResults() could take dump_json_test_results as a parameter and .dump_to_file could be .write() or something (and the no-op test_results could have an empty .write()).

2016-12-05 16:50 UTC, pbos commented on gtest-parallel
> +  test_results.dump_to_file(options.dump_json_test_results)
Or call it .close() on CollectTestResults, and it writes on close, that makes sense to me. @kwiberg probably has a better method name, but I think CollectTestResults should hold onto the file handle.

2016-12-05 16:57 UTC, ehlemur commented on gtest-parallel
> +  test_results.dump_to_file(options.dump_json_test_results)
What about dump_to_file_and_close()?

2016-12-05 16:57 UTC, ehlemur commented
PTAL :)

2016-12-05 17:29 UTC, pbos requested changes
dump_to_file_and_close sounds great

2016-12-05 17:29 UTC, pbos commented on gtest-parallel
> +  test_results.dump_to_file_and_close()
Implement this in the IgnoreTestResults() class too and make it unconditional.

Also add an empty line before this one.

2016-12-05 17:29 UTC, pbos commented on gtest-parallel
> +  test_results = CollectTestResults(options.dump_json_test_results)
I think this was better before as CTR(arg) if opt.dump... else ITR().

2016-12-05 17:29 UTC, pbos commented on gtest-parallel
> +    pass
Add dump_to_file_and_close(self)

2016-12-05 17:38 UTC, ehlemur commented on gtest-parallel
> +                else CollectTestResults(options.dump_json_test_results))
What about like this, so the line doesn't get too long?

2016-12-05 17:40 UTC, pbos approved these changes

2016-12-05 17:40 UTC, pbos commented
I want @kwiberg to OK it as well, then we can squash this. :)

Thanks!

2016-12-06 20:17 UTC, kwiberg approved these changes
Looks good to me!

2016-12-06 20:19 UTC, merged