Add a timeout option to gtest-parallel.
google/gtest-parallel pull request #18
Opened 2017-02-06 17:48 UTC by ehlemur

Stop the tests' execution once the timeout has been exceeded.

2017-02-06 17:49 UTC, ehlemur commented on gtest-parallel
> +  def interrupt(self):
Maybe we could get rid of __sigint_handler and use this method instead?
Is interrupt a good name?

2017-02-06 17:49 UTC, ehlemur commented
@pbos @kwiberg

2017-02-07 09:04 UTC, kwiberg requested changes

2017-02-07 09:04 UTC, kwiberg commented on gtest-parallel
> +  timeout.start()
For paranoia reasons, it's probably better to start the timeout before you start the worker threads. So IOW, maybe move the "workers =" line into the try...except, below this line?

2017-02-07 09:04 UTC, kwiberg commented on gtest-parallel
> +                       'timeout.')
Document what the integer means. Seconds?

2017-02-07 09:04 UTC, kwiberg commented on gtest-parallel
> +
Spurious newline?

2017-02-07 09:04 UTC, kwiberg commented on gtest-parallel
> +  def interrupt(self):
Yes, interrupt is a good name. But __sigint_handler is registered as a sigint handler, so if you eliminated it you'd have to... yes, you could register a lambda as sigint handler instead; the lambda would just ignore the signal_num and frame arguments and call interrupt(). Do that.

2017-02-07 09:04 UTC, kwiberg commented on gtest-parallel
> +    interruptions = set(self.started).difference(set(self.finished))
Can also be written as
`set(self.started) - set(self.finished)`

2017-02-07 09:04 UTC, kwiberg commented on gtest-parallel
> +    self.print_tests("INTERRUPTED TESTS", interruptions)
1. Don't we already print failed tests?
2. When you print lists of tests, would it make sense to sort them first?

2017-02-07 10:52 UTC, ehlemur commented
PTAL :smile:

2017-02-07 12:00 UTC, ehlemur commented
I think it's more readable the way it is.

2017-02-07 12:01 UTC, kwiberg approved these changes
lgtm

2017-02-07 12:05 UTC, merged