Create find_tests() and execute_tasks() functions + some refactoring.
google/gtest-parallel pull request #25
Opened 2017-04-27 18:43 UTC by ehlemur

2017-04-27 18:43 UTC, ehlemur commented
@pbos @kwiberg 
Please take a look :)

2017-04-27 20:12 UTC, pbos commented
@kwiberg would you mind taking this one? :)

2017-04-28 08:57 UTC, kwiberg approved these changes
Would you like to make changes, or merge as is?

2017-04-28 08:57 UTC, kwiberg commented on gtest-parallel
> +        task.run()
I think you can write this as something like
```
  while True:
    with self.task_lock:
      if self.task_id < len(self.tasks):
        task = self.tasks[self.task_id]
        self.task_id += 1
      else:
        return
    task.run()
```

2017-04-28 08:57 UTC, kwiberg commented on gtest-parallel
> +    [t.join() for t in workers]
Less compactly, but more conventionally, written as
```
for t in workers:
  t.join()
```
I know you've only moved this line, though, so feel free to not change it.

2017-04-28 09:41 UTC, ehlemur commented
I'll make those changes.

2017-04-28 10:01 UTC, ehlemur commented
Don't merge yet, please

2017-04-28 10:05 UTC, kwiberg requested changes

2017-04-28 10:05 UTC, kwiberg commented on gtest-parallel
> +        task = None
This line isn't necessary anymore, is it?

2017-04-28 10:13 UTC, ehlemur commented on gtest-parallel
> +        task = None
Right.

2017-04-28 10:33 UTC, ehlemur commented
Please take a look

2017-04-29 07:36 UTC, kwiberg approved these changes

2017-04-29 07:37 UTC, merged