Add TaskManager class and support to repeat failed tests.
google/gtest-parallel pull request #26
Opened 2017-05-02 13:52 UTC by ehlemur

TaskManager is responsible for dealing with times, logger and test_results, keeping track of what tasks have been executed and which tasks should be repeated.
The only semantic change should be that now, when we repeat the tasks with the --repeat flag, we wait until we finish executing the test to schedule the next execution. This is because running several instances of a test at the same time might cause problems.

2017-05-02 13:52 UTC, ehlemur commented
@pbos @kwiberg 
Please take a look :)

2017-05-02 15:33 UTC, pbos commented
--repeat needs to support running the same test in parallel, --gtest_filter=OneTest.OneTest -r2000 should run that same test in parallel.

2017-05-02 16:54 UTC, ehlemur commented
Ok, done.
Retries are done immediately, in the same thread.

2017-05-03 10:39 UTC, kwiberg requested changes
Looks good.

2017-05-03 10:39 UTC, kwiberg commented on gtest-parallel
> +import collections
This appears to be unused.

2017-05-03 10:39 UTC, kwiberg commented on gtest-parallel
>  class Task(object):
Could you add a comment describing what this class does? (It should already have been there. This patch just makes the problem a bit worse.)

2017-05-03 10:39 UTC, kwiberg commented on gtest-parallel
> +class TaskManager(object):
And a comment for this class too?

2017-05-03 11:13 UTC, ehlemur commented
Please take a look.

2017-05-03 12:12 UTC, kwiberg approved these changes

2017-05-03 12:13 UTC, merged