Add tests to gtest-parallel.
google/gtest-parallel pull request #31
Opened 2017-05-11 15:06 UTC by ehlemur

2017-05-11 15:07 UTC, ehlemur commented
@pbos @kwiberg 
PTAL.

2017-05-11 15:30 UTC, pbos commented
Can you add these tests one at a time so they're easier to review? :)

2017-05-11 15:58 UTC, ehlemur commented
Ok :)
PTAL

2017-05-11 17:07 UTC, pbos commented on gtest_parallel.py
> +  def __init__(self, times, logger, test_results, task_factory, times_to_retry,
Is this a factory, or should this be called task_class? Python kinda makes this the same thing. WDYT?

2017-05-11 17:08 UTC, pbos commented on gtest_parallel_tests.py
> +import collections
Add license header w/ 2017.

2017-05-11 17:09 UTC, pbos commented on gtest_parallel.py
> +  def __init__(self, times, logger, test_results, task_factory, times_to_retry,
Ignore this, I think it's fine. :)

2017-05-12 08:40 UTC, kwiberg requested changes
Looks good, except the copyright year as pbos@ said.

2017-05-12 09:34 UTC, ehlemur commented
PTAL :)

2017-05-12 15:13 UTC, merged